Repository openhab/openhab-js, pull requests merged in 2023-02, with the labels that each got.

#233 [items] Allow Item lookup by name directly on the `items` namespace
  CHANGELOG.md
  README.md
  items/items.js
  types/items/items.d.ts
  types/items/items.d.ts.map
Labels: enhancement

#234 [items] Add `numericState` & `quantityState` to `Item` & `HistoricItem`
  CHANGELOG.md
  README.md
  items/item-history.js
  items/items.js
  types/items/item-history.d.ts
  types/items/item-history.d.ts.map
  types/items/items.d.ts
  types/items/items.d.ts.map
Labels: enhancement

#223 [items] Extend `metadata` & `itemchannellink` APIs
  CHANGELOG.md
  items/item-history.js
  items/items.js
  items/metadata/itemchannellink.js
  items/metadata/metadata.js
  types/items/item-history.d.ts.map
  types/items/items.d.ts
  types/items/items.d.ts.map
  types/items/metadata/itemchannellink.d.ts
  types/items/metadata/itemchannellink.d.ts.map
  types/items/metadata/metadata.d.ts
  types/items/metadata/metadata.d.ts.map
Labels: enhancement

#236 [actions] Semantics: Recommend to use `Item.semantics`
  actions.js
  types/actions.d.ts
  types/actions.d.ts.map
Labels: documentation

#237 [osgi] Migrate from addon to core lifecycle tracker
  CHANGELOG.md
  osgi.js
  test/@runtime.mock.js
  test/osgi.spec.js
Labels: enhancement

#244 [utils] Add access to library version
  CHANGELOG.md
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
Labels: enhancement

#243 [items] Fix error handling for `quantityState`
  CHANGELOG.md
  items/item-history.js
  items/items.js
  types/items/item-history.d.ts.map
  types/items/items.d.ts.map
Labels: bug

#249 [items] Fix `ItemHistory.latestState` doesn’t return string
  CHANGELOG.md
  items/item-history.js
  types/items/item-history.d.ts
  types/items/item-history.d.ts.map
Labels: bug
