Repository openhab/openhab-js, pull requests merged in 2023-09, with the labels that each got.

#294 README: Minor rewording
  README.md
Labels: documentation

#291 [rules] Rule Builder: Add DateTime & TimeOfDay triggers & Improve type defs
  README.md
  rules/condition-builder.js
  rules/operation-builder.js
  rules/rule-builder.js
  rules/trigger-builder.js
  triggers.js
  types/rules/condition-builder.d.ts
  types/rules/condition-builder.d.ts.map
  types/rules/operation-builder.d.ts
  types/rules/operation-builder.d.ts.map
  types/rules/rule-builder.d.ts
  types/rules/rule-builder.d.ts.map
  types/rules/trigger-builder.d.ts
  types/rules/trigger-builder.d.ts.map
  types/triggers.d.ts
  types/triggers.d.ts.map
Labels: enhancement

#296 [rules] Fix null-access when getting event information
  rules/rules.js
Labels: bug, regression

#297 [rules] Rule Builder: Add fromOn & fromOff to Item trigger config
  rules/trigger-builder.js
  types/rules/trigger-builder.d.ts
  types/rules/trigger-builder.d.ts.map
Labels: enhancement

#298 [items] Use registry instead of provider
  items/items.js
  items/metadata/itemchannellink.js
  types/items/items.d.ts
  types/items/items.d.ts.map
Labels: enhancement
