Repository openhab/openhab-js, pull requests merged in 2023-01, with the labels that each got.

#227 [time] Add isBefore*/isAfter* convenience methods
  CHANGELOG.md
  README.md
  test/time.spec.js
  time.js
Labels: enhancement

#228 [items] Return HistoricItem from persistence where applicable
  CHANGELOG.md
  README.md
  items/item-history.js
  types/items/item-history.d.ts
  types/items/item-history.d.ts.map
Labels: enhancement, breaking change

#229 fix executeCommandLine without a Duration
  README.md
Labels: documentation

#230 [items] Metadata: Accept both Item and Item name
  .gitignore
  CHANGELOG.md
  helpers.js
  items/metadata/itemchannellink.js
  items/metadata/metadata.js
  types/items/metadata/itemchannellink.d.ts
  types/items/metadata/itemchannellink.d.ts.map
  types/items/metadata/metadata.d.ts
  types/items/metadata/metadata.d.ts.map
Labels: enhancement
