Repository openhab/openhab-js, pull requests merged in 2024-06, with the labels that each got.

#336 README: Fix Item persistene reference
  README.md
Labels: documentation

#338 [items] Improve JSDoc and README for `ItemPersistence#persist`
  README.md
  src/items/item-persistence.js
  types/items/item-persistence.d.ts
  types/items/item-persistence.d.ts.map
Labels: documentation

#339 [items] ItemPersistence: Convert state to primitive type in `persist` method
  src/helpers.js
  src/items/item-persistence.js
  src/items/items.js
  types/items/item-persistence.d.ts
  types/items/item-persistence.d.ts.map
Labels: bug

#340 GHA build: Upload webpacked library versions as artifact
  .github/workflows/build.yaml
Labels: infrastructure

#341 [items] ItemPersistence: Add support for persisting TimeSeries
  README.md
  src/helpers.js
  src/items/item-persistence.js
  src/items/items.js
  src/items/time-series.js
  types/items/item-persistence.d.ts
  types/items/item-persistence.d.ts.map
  types/items/items.d.ts
  types/items/items.d.ts.map
  types/items/time-series.d.ts
  types/items/time-series.d.ts.map
Labels: enhancement

#342 [items] TimeSeries: Add support for using Instant as timestamp
  README.md
  src/items/time-series.js
  types/items/time-series.d.ts
  types/items/time-series.d.ts.map
Labels: enhancement

#343 [items] Item: Fix sendCommandIfDifferent fails to compare Quantity
  src/items/items.js
  types/items/items.d.ts.map
Labels: bug

#348 [helpers] Fix isInstant & Improve helpers in general
  src/helpers.js
  src/items/time-series.js
  src/time.js
  test/quantity.spec.js
  test/time.spec.js
  types/items/time-series.d.ts
  types/items/time-series.d.ts.map
  types/time.d.ts
Labels: bug

#350 [items] ItemPersistence: Add lastChange and nextChange methods
  README.md
  src/items/item-persistence.js
  types/items/item-persistence.d.ts
  types/items/item-persistence.d.ts.map
Labels: enhancement

#351 [actions] Add notification builders & Mark some actions deprecated as replaced by better APIs
  README.md
  src/actions/actions.js
  src/actions/notification-builder.js
  src/actions/package.json
  test/jest.setup.js
  test/notification-builder.spec.js
  test/openhab.mock.js
  types/actions.d.ts.map
  types/actions/actions.d.ts
  types/actions/actions.d.ts.map
  types/actions/notification-builder.d.ts
  types/actions/notification-builder.d.ts.map
  types/openhab-js.d.ts
Labels: enhancement
