Repository openhab/openhab-js, pull requests merged in 2024-12, with the labels that each got.

#402 [cache] Advise to not store JavaScript objects in shared cache
  README.md
  src/cache.js
  types/cache.d.ts.map
Labels: enhancement

#405 CI build: Verify there are no changed files
  .github/workflows/build.yaml
Labels: infrastructure

#408 Use configured time-zone when converting `DateTimeType` to `ZonedDateTime`
  src/time.js
Labels: enhancement

#411 README: Improve rule builder trigger builder docs
  README.md
Labels: documentation
