Repository openhab/openhab-js, pull requests merged in 2025-03, with the labels that each got.

#419 Add example how to hide notifications again
  README.md
Labels: documentation

#421 [items] Fix sendCommandIfDifferent fails for Dimmer/Number Items with string commands
  src/items/items.js
  types/items/items.d.ts.map
  types/rules/operation-builder.d.ts
  types/rules/operation-builder.d.ts.map
Labels: bug

#422 [time] toZDT: Add support for Instant & toInstant: Add support for epoch millis
  README.md
  src/time.js
  test/java.mock.js
  test/jest.setup.js
  test/time.spec.js
  types/time.d.ts
  types/time.d.ts.map
Labels: enhancement

#423 [items] Add Instant as valid parameter type for sendCommand & postUpdate
  src/items/items.js
  types/items/items.d.ts
  types/items/items.d.ts.map
  types/quantity.d.ts
  types/quantity.d.ts.map
Labels: enhancement

#401 Extend Persistence Extensions with Riemann Sums
  README.md
  src/items/item-persistence.js
  types/items/item-persistence.d.ts
  types/items/item-persistence.d.ts.map
Labels: enhancement
