Repository openhab/openhab-js, pull requests merged in 2025-05, with the labels that each got.

#435 [cache] Allow returning null from supplier function
  src/cache.js
  types/cache.d.ts
  types/cache.d.ts.map
Labels: bug

#436 Markdown Checks: Upgrade actions & Ignore commit/PR links
  .github/workflows/markdown.yaml
  .github/workflows/markdownlint.yaml
  CONTRIBUTING.md
  mlc_config.json
Labels: infrastructure

#433 [items] Item: Add numeric and quantity variants for previousState
  README.md
  src/items/items.js
  types/items/items.d.ts
  types/items/items.d.ts.map
  types/items/metadata/itemchannellink.d.ts
  types/items/metadata/itemchannellink.d.ts.map
  types/items/metadata/metadata.d.ts
  types/items/metadata/metadata.d.ts.map
  types/quantity.d.ts
  types/quantity.d.ts.map
  types/rules/operation-builder.d.ts
  types/rules/operation-builder.d.ts.map
  types/triggers.d.ts
  types/triggers.d.ts.map
Labels: enhancement

#437 [items] Refactor state factory methods into shared helpers to reduce code duplication
  .gitignore
  src/helpers.js
  src/items/helpers.js
  src/items/item-persistence.js
  src/items/items.js
  types/items/item-persistence.d.ts.map
  types/items/items.d.ts.map
  types/rules/operation-builder.d.ts
  types/rules/operation-builder.d.ts.map
  types/triggers.d.ts
  types/triggers.d.ts.map
Labels: enhancement

#438 Move Markdown CI checks config into .github dir
  .github/markdownlint.yaml
  .github/mlc_config.json
  .github/workflows/markdown.yaml
  .npmignore
Labels: infrastructure

#439 [items] ItemPersistence: Fix Quantity state missing
  src/items/item-persistence.js
Labels: bug, regression
